#!/bin/bash

function ts {
	date +"%Y-%m-%d_%H:%M:%S"
}

DEST=$1
shift
CFGLIST=$1

if [ "$1" = "" ]; then
	echo "need args: destination-dir <list of files>"
	exit 1
fi

echo "Save Configuration Files, Destination = $DEST"

d="$DEST/$(ts)"

mkdir -p "$d"
if [ $? -ne 0 ]; then
	echo "Error creating directory: $d"
	exit 1
fi

for file in $CFGLIST;
do
	echo "save $file"
	cp "$file" "$d"
	if [ $? -ne 0 ]; then
		echo "ERROR copying file"
		exit 1
	fi
done
