FROM debian:buster-slim

ADD ./docker-entrypoint.sh /

#---preparation---
RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
RUN apt-get update
RUN apt-get install -y make gcc g++ libssl-dev git libcurl4-gnutls-dev libusb-dev python3-dev zlib1g-dev wget vim sudo procps
RUN adduser --disabled-password --gecos '' app

# ALL STEPS FROM https://www.domoticz.com/wiki/Build_Domoticz_from_source
#---step: cmake---
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0-rc2/cmake-3.16.0-rc2.tar.gz
RUN tar -xzvf cmake-3.16.0-rc2.tar.gz
RUN rm cmake-3.16.0-rc2.tar.gz
RUN cd /cmake-3.16.0-rc2 && ./bootstrap && make && make install
RUN rm -Rf /cmake-3.16.0

#---step: boost---
RUN mkdir /boost
RUN cd /boost && wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
RUN cd /boost && tar xfz boost_1_71_0.tar.gz
RUN cd /boost/boost_1_71_0 && ./bootstrap.sh
RUN cd /boost/boost_1_71_0 && ./b2 stage threading=multi link=static --with-thread --with-system
RUN cd /boost/boost_1_71_0 && ./b2 install threading=multi link=static --with-thread --with-system
RUN rm -Rf /boost

#---step: domoticz---
RUN git clone https://github.com/domoticz/domoticz.git dev-domoticz
RUN cd /dev-domoticz && cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt -DUSE_OPENSSL_STATIC="NO" && make

#--step: startup--
RUN sed -i 's/^USERNAME=.*$/USERNAME=app/' /dev-domoticz/domoticz.sh
RUN sed -i 's/^DAEMON=.*$/DAEMON=\/home\/app\/domoticz\/$NAME/' /dev-domoticz/domoticz.sh
RUN sed -i 's/^DAEMON_ARGS="-daemon".*$/DAEMON_ARGS="-daemon -www %iport% -dbase %vdst_doubesc%\/domoticz.db"/' /dev-domoticz/domoticz.sh
RUN cp /dev-domoticz/domoticz.sh /etc/init.d
RUN chmod +x /etc/init.d/domoticz.sh

#---step: move to user---
RUN mv /dev-domoticz /home/app/domoticz
RUN chown -R app.app /home/app/domoticz
RUN mkdir -p %vdst%
RUN chown -R app.app %vdst%
VOLUME %vdst%

#---step: finalize--
EXPOSE %iport%
CMD /docker-entrypoint.sh
